import base64
from pathlib import Path
import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="PROJECT : LOGIC // TUTORIAL", layout="wide", initial_sidebar_state="collapsed")
font_path = next((Path(n) for n in ("neodgm.ttf", "neodgm(2).ttf", "../neodgm.ttf", "../neodgm(2).ttf") if Path(n).exists()), None)
font_b64 = base64.b64encode(font_path.read_bytes()).decode() if font_path else ""

# Tutorial page intentionally has no timer.
html = f'''<!doctype html><html><head><meta charset="utf-8"><style>
@font-face{{font-family:Neo;src:url(data:font/ttf;base64,{font_b64}) format("truetype")}}
*{{box-sizing:border-box;user-select:none}}html,body{{margin:0;width:100%;height:100%;overflow:hidden;background:#000;color:#fff;font-family:Neo,monospace}}
.game{{position:relative;width:100vw;height:100vh;background:#000;outline:0}}
.top{{position:absolute;top:24px;left:28px;z-index:20;font-size:18px;letter-spacing:1px}}.stage{{position:absolute;top:52px;left:28px;z-index:20;color:#777;font-size:13px;letter-spacing:1px}}
.area{{position:absolute;top:90px;left:28px;right:28px;bottom:70px;overflow:hidden;background:#080808;background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:40px 40px}}
.room{{position:absolute;left:7%;top:8%;width:86%;height:82%;border:1px solid rgba(255,255,255,.12);overflow:hidden}}
.object{{position:absolute;display:flex;align-items:center;justify-content:center;background:#0b0b0b;border:1px solid rgba(255,255,255,.22);color:#777;font-size:12px;text-align:center}}
.monitor{{left:43%;top:13%;width:14%;height:12%}}.desk{{left:35%;top:62%;width:30%;height:12%}}.terminal{{left:18%;top:35%;width:14%;height:17%}}
.exit-wall{{right:0;top:35%;width:8%;height:30%;background:#0d0d0d;border-left:1px solid #555}}
.exit-plan{{font-size:10px;line-height:1.7;color:#aaa;text-align:center;writing-mode:vertical-rl;letter-spacing:1px}}
.player{{position:absolute;width:24px;height:24px;left:50%;top:43%;transform:translate(-50%,-50%);background:#fff;z-index:60;box-shadow:0 0 0 1px #000}}
.label{{position:absolute;bottom:-22px;left:50%;transform:translateX(-50%);white-space:nowrap;font-size:10px;color:#555}}
.echo{{position:absolute;left:50%;bottom:4%;transform:translateX(-50%);width:min(760px,82vw);min-height:105px;background:#050505;border:1px solid #555;padding:18px 22px;z-index:100;cursor:pointer}}
.echo-name{{font-size:13px;margin-bottom:10px;letter-spacing:1px}}.echo-text{{font-size:13px;color:#aaa;line-height:1.8;padding-right:30px;min-height:48px}}.echo-next{{position:absolute;right:16px;bottom:12px;color:#555;font-size:10px}}
.status{{position:absolute;left:28px;bottom:24px;color:#777;font-size:14px;z-index:120}}
.arrow{{position:absolute;right:9%;top:43%;font-size:24px;color:#fff;z-index:80;animation:arrow 1.2s ease-in-out infinite;display:none}}.arrow.show{{display:block}}@keyframes arrow{{0%,100%{{transform:translateY(-8px);opacity:.45}}50%{{transform:translateY(8px);opacity:1}}}}
.overlay{{position:absolute;inset:0;background:rgba(0,0,0,.94);z-index:300;display:none;align-items:center;justify-content:center}}.overlay.show{{display:flex}}
.panel{{width:min(560px,82vw);background:#050505;border:1px solid #555;padding:30px}}.panel h2{{font-size:20px;font-weight:400;margin:0 0 8px}}.sub{{font-size:11px;color:#666;margin-bottom:24px}}.display{{min-height:75px;padding:16px;border:1px solid #292929;background:#090909;color:#888;font-size:12px;line-height:1.8;margin-bottom:18px}}
input{{width:100%;height:48px;border:1px solid #555;background:#000;color:#fff;font:18px Neo;text-align:center;letter-spacing:5px;outline:0}}.buttons{{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}}button{{border:0;border-radius:0;background:#000;color:#fff;font:13px Neo;padding:0;cursor:pointer}}.buttons button{{width:120px;height:40px}}button:hover{{background:#fff;color:#000}}
.reader{{position:absolute;inset:0;background:rgba(0,0,0,.96);z-index:310;display:none;align-items:center;justify-content:center}}.reader.show{{display:flex}}.reader-panel{{width:min(640px,88vw);border:1px solid #555;background:#050505;padding:28px;text-align:center}}.reader-zone{{margin:28px auto;width:360px;height:110px;border:1px dashed #555;display:flex;align-items:center;justify-content:center;color:#666;position:relative}}.card{{position:absolute;width:150px;height:82px;background:#fff;color:#000;left:20px;top:14px;display:flex;align-items:center;justify-content:center;font:18px Neo;cursor:grab;z-index:2}}.reader-slot{{width:180px;height:56px;border:1px solid #777;display:flex;align-items:center;justify-content:center;color:#aaa}}.success{{color:#fff;margin-top:16px;min-height:20px}}
@media(max-width:700px){{.top{{top:18px;left:16px;font-size:14px}}.stage{{top:40px;left:16px;font-size:11px}}.area{{top:68px;left:16px;right:16px;bottom:58px;background-size:30px 30px}}.status{{left:16px;bottom:18px;font-size:11px}}.echo{{width:88vw;min-height:110px;padding:15px 17px}}.echo-text{{font-size:10px}}.reader-zone{{width:90%;height:100px}}}}
</style></head><body>
<div class="game" id="game" tabindex="0"><div class="top">PROJECT : LOGIC</div><div class="stage">STAGE TUTORIAL</div>
<div class="area"><div class="room"><div class="object monitor" id="monitor">MONITOR<div class="label">CENTRAL MONITOR</div></div><div class="object desk" id="desk">DESK<div class="label">RESEARCH DESK</div></div><div class="object terminal" id="terminal">COMPUTER<div class="label">SECURITY COMPUTER</div></div><div class="object exit-wall" id="exit"><div class="exit-plan">[EXIT]<br>SECURITY ROOM</div></div><div class="arrow" id="arrow">↓</div><div class="player" id="player"></div></div>
<div class="echo" id="echo"><div class="echo-name">ECHO // SYSTEM AI</div><div class="echo-text" id="echoText"></div><div class="echo-next" id="echoNext">[ SPACE ]</div></div>
<div class="status" id="status">ECHO SYSTEM // ONLINE</div></div>
<div class="overlay" id="computer"><div class="panel"><h2>SECURITY COMPUTER</h2><div class="sub">ECHO TERMINAL // AUTHORIZATION REQUIRED</div><div class="display" id="display">ECHO가 전달한 인증 번호를 입력하십시오.</div><input id="code" type="text" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="----"><div class="buttons"><button id="close">CLOSE</button><button id="submit">ENTER</button></div></div></div>
<div class="reader" id="reader"><div class="reader-panel"><h2>SECURITY CARD READER</h2><div class="sub">ACCESS KEY를 리더 영역으로 드래그하십시오.</div><div class="reader-zone" id="zone"><div class="reader-slot">CARD READER</div><div class="card" id="card">ACCESS KEY</div></div><div class="success" id="readerStatus"></div><div class="buttons"><button id="readerClose">CLOSE</button></div></div></div>
</div>
<script>
const root=document.getElementById('game'),player=document.getElementById('player'),terminal=document.getElementById('terminal'),desk=document.getElementById('desk'),exit=document.getElementById('exit'),echo=document.getElementById('echo'),text=document.getElementById('echoText'),next=document.getElementById('echoNext'),status=document.getElementById('status'),computer=document.getElementById('computer'),code=document.getElementById('code'),display=document.getElementById('display'),reader=document.getElementById('reader'),card=document.getElementById('card'),zone=document.getElementById('zone'),arrow=document.getElementById('arrow');
const keys={w:false,a:false,s:false,d:false}; let x=50,y=43,step=0,typing=false,charIndex=0,typeTimer=null,computerUnlocked=false,keyObtained=false,interactionOpen=false,dragging=false,dragOffsetX=0,dragOffsetY=0;
const codeAnswer='4172';
const messages=['연결이 확인되었습니다. 이 시설의 현재 상황을 설명하겠습니다.','현재 당신은 연구시설의 CONTROL ROOM에 있습니다.','시설의 보안 시스템이 비정상적으로 작동하고 있습니다. 이곳에서 탈출하려면 순서대로 보안 절차를 복구해야 합니다.','걱정하지 마십시오. 제가 필요한 절차를 안내하겠습니다.','우선 왼쪽의 SECURITY COMPUTER로 이동하십시오. 가까이 다가가면 E 키를 눌러 조사할 수 있습니다.','좋습니다. COMPUTER를 조사하면 인증 번호를 입력할 수 있습니다.','인증 번호는 4172입니다. 화면에 표시된 입력창에 제가 말한 숫자를 그대로 입력하십시오.','인증이 완료되었습니다. 이제 연구용 책상으로 이동하십시오.','책상에서 ACCESS KEY를 획득할 수 있습니다. 가까이 다가간 뒤 E 키를 누르십시오.','ACCESS KEY가 확인되었습니다. 오른쪽의 [EXIT] SECURITY ROOM으로 이동하십시오. 카드 리더가 나타나면 ACCESS KEY를 사용하십시오.'];
function showMessage(i){step=i; charIndex=0;typing=true;text.textContent='';next.textContent='[ SPACE ]';clearInterval(typeTimer);typeTimer=setInterval(()=>{if(charIndex<messages[step].length){text.textContent+=messages[step][charIndex++]}else{clearInterval(typeTimer);typing=false;next.textContent='[ SPACE ]'}} ,32)}
function space(){if(interactionOpen)return;if(typing){clearInterval(typeTimer);text.textContent=messages[step];charIndex=messages[step].length;typing=false;return}if(step<messages.length-1){if(step===4 && !near('terminal'))return; if(step===6 && !computerUnlocked)return; if(step===8 && !keyObtained)return; showMessage(step+1)}else echo.style.display='none'}
function near(el){const r=el.getBoundingClientRect(),rr=root.getBoundingClientRect(),px=rr.left+x/100*rr.width,py=rr.top+y/100*rr.height,cx=r.left+r.width/2,cy=r.top+r.height/2;return Math.hypot(px-cx,py-cy)<110}
function msg(){if(near(terminal))status.textContent='E // SECURITY COMPUTER';else if(near(desk))status.textContent='E // RESEARCH DESK';else if(near(exit))status.textContent='E // [EXIT] SECURITY ROOM';else status.textContent='ECHO SYSTEM // ONLINE'}
function blocked(){status.textContent='접근할 수 없는 과정입니다.';setTimeout(()=>status.textContent='ECHO SYSTEM // ONLINE',1200)}
function interact(){if(interactionOpen)return;if(near(terminal)){if(step<4){blocked();return}openComputer();return}if(near(desk)){if(!computerUnlocked){blocked();return}if(!keyObtained){keyObtained=true;arrow.classList.add('show');showMessage(9);status.textContent='SYSTEM // ACCESS KEY ACQUIRED';return}return}if(near(exit)){if(!keyObtained){blocked();return}openReader();return}}
function openComputer(){interactionOpen=true;computer.classList.add('show');code.value='';display.innerHTML='ECHO가 전달한 인증 번호를 입력하십시오.';code.focus();clearKeys()}
function closeComputer(){interactionOpen=false;computer.classList.remove('show');root.focus()}
document.getElementById('submit').onclick=()=>{if(code.value.trim()===codeAnswer){computerUnlocked=true;display.innerHTML='AUTHORIZATION ACCEPTED<br><br>SECURITY ACCESS KEY가 생성되었습니다.';status.textContent='COMPUTER // AUTHORIZATION ACCEPTED';setTimeout(closeComputer,650)}else display.innerHTML='ACCESS DENIED<br><br>ECHO가 알려준 숫자를 그대로 입력하십시오.'};document.getElementById('close').onclick=closeComputer;code.onkeydown=e=>{if(e.key==='Enter')document.getElementById('submit').click();if(e.key==='Escape')closeComputer()};
function openReader(){interactionOpen=true;reader.classList.add('show');card.style.left='20px';card.style.top='14px';document.getElementById('readerStatus').textContent='';clearKeys()}
document.getElementById('readerClose').onclick=()=>{reader.classList.remove('show');interactionOpen=false;root.focus()};
card.addEventListener('pointerdown',e=>{dragging=true;card.setPointerCapture(e.pointerId);const r=card.getBoundingClientRect();dragOffsetX=e.clientX-r.left;dragOffsetY=e.clientY-r.top;card.style.cursor='grabbing'});card.addEventListener('pointermove',e=>{if(!dragging)return;const zr=zone.getBoundingClientRect(),rr=card.getBoundingClientRect();card.style.left=(e.clientX-zr.left-dragOffsetX)+'px';card.style.top=(e.clientY-zr.top-dragOffsetY)+'px'});card.addEventListener('pointerup',e=>{dragging=false;card.style.cursor='grab';const a=card.getBoundingClientRect(),b=zone.querySelector('.reader-slot').getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top){document.getElementById('readerStatus').textContent='ACCESS ACCEPTED // SECURITY ROOM UNLOCKED';setTimeout(()=>{window.parent.location.href=new URL('3_Control_Room.py',window.parent.location.href).href},900)}});
function clearKeys(){Object.keys(keys).forEach(k=>keys[k]=false)}
function collides(nx,ny){const rr=root.getBoundingClientRect(),px=rr.left+nx/100*rr.width,py=rr.top+ny/100*rr.height;for(const el of [terminal,desk,document.getElementById('monitor'),exit]){const r=el.getBoundingClientRect();if(px+12>r.left&&px-12<r.right&&py+12>r.top&&py-12<r.bottom)return true}return false}
function move(){if(!interactionOpen){let nx=x+(keys.d-keys.a)*.65,ny=y+(keys.s-keys.w)*.65;nx=Math.max(2,Math.min(98,nx));ny=Math.max(2,Math.min(98,ny));if(!collides(nx,y))x=nx;if(!collides(x,ny))y=ny;player.style.left=x+'%';player.style.top=y+'%';msg()}requestAnimationFrame(move)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k===' '){space();e.preventDefault();return}if(k==='e'){interact();e.preventDefault();return}if(k==='escape'&&interactionOpen){if(computer.classList.contains('show'))closeComputer();else{reader.classList.remove('show');interactionOpen=false;root.focus()}e.preventDefault();return}if(['w','a','s','d'].includes(k)&&!interactionOpen){keys[k]=true;e.preventDefault()}} ,true);window.addEventListener('keyup',e=>{if(['w','a','s','d'].includes(e.key.toLowerCase()))keys[e.key.toLowerCase()]=false},true);root.addEventListener('pointerdown',()=>{if(!interactionOpen)root.focus()});showMessage(0);root.focus();requestAnimationFrame(move);
</script></body></html>'''
components.html(html,height=1000,scrolling=False)
